Добавление тех.задания
dasha195/GAMES pull request #2
Opened 2024-12-16 08:22 UTC by dasha195

2024-12-18 18:45 UTC, KseniaStarostina17 approved these changes
OK

2024-12-19 07:30 UTC, Laggon requested changes

2024-12-19 07:30 UTC, Laggon commented on TZ.md
> +• Разработать графический интерфейс пользователя игры, включающий игровое поле, 9 кнопок, расположенных в виде 3x3 сетки, индикатор текущего игрока и кнопку перезапуска игры.
Если использовать списки, то в Markdown есть поддержка списков, стоит использовать их

В других местах тоже исправить

2024-12-19 07:32 UTC, Laggon commented
Также не у всех участников запросили ревью

2024-12-19 07:59 UTC, RubcovaMM approved these changes
Все замечания учтены. Задание сделано хорошо.

2024-12-19 10:44 UTC, Laggon approved these changes

2024-12-19 10:53 UTC, merged