Добавление тех.задания для игры "Змейка"
dasha195/GAMES pull request #9
Opened 2024-12-16 09:31 UTC by dasha195

2024-12-18 18:49 UTC, KseniaStarostina17 approved these changes
BEAUTIFUL!!

2024-12-19 07:32 UTC, Laggon commented
Также не у всех участников запросили ревью

2024-12-19 07:35 UTC, Laggon requested changes
Также не у всех участников запрошено ревью

2024-12-19 07:35 UTC, Laggon commented on TZ.md
> +• Создать графический интерфейс игры: игровое поле в виде сетки, отображение змейки и "еды".
Если использовать списки, то в Markdown есть поддержка списков, стоит использовать их

В других местах тоже исправить

2024-12-19 07:35 UTC, Laggon commented
Нужно указать ответственного

2024-12-19 08:00 UTC, RubcovaMM approved these changes
Отличная работа.

2024-12-19 10:45 UTC, Laggon approved these changes

2024-12-19 11:05 UTC, merged